name: R_conda
channels:
  - conda-forge
  # - bioconda
  - r
dependencies:
  - r-base=4.0.*
  - r-tidyverse=1.3.*
  - r-openxlsx=4.2.* 
  # - rstudio=1.1.*
  # - r-egg=0.4.*
  # - r-pheatmap=1.0.*
  # - r-pdftools=2.3.*

